#!/usr/bin/env node
const express = require('express');
const bodyParser = require('body-parser');
const generateFromHtml = require('./generateFromHtml');

const app = express();
const port = process.env.PUPPETEER_PORT || 3900;
const host = process.env.PUPPETEER_HOST || '127.0.0.1';

app.use(bodyParser.json({limit: '500mb'}));

app.post('/echo', (req, res) => {
    const html = req.body.html;
    res.send(html);
});

app.post('/generate', async (req, res) => {
    try {
        const pdfFilepath = await generateFromHtml(req.body);
        res.sendFile(pdfFilepath);
    } catch (err) {
        console.error(err);
        res.status(500).send('Error while generating PDF');
    }
});

app.listen(port, host, () => {
    console.log(`Listening to ${host}:${port}`);
});
